[package]
name = "cminusone"
version = "0.1.28"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "cminusone"
crate-type = ["cdylib"]

[dependencies]
minusone = { path = ".." }
widestring = "1.1.0"
