# This is a basic workflow to help you get started with Actions

name: Unit Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: "*"
    tags : "v*.*"
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ "Linux", "self-hosted" ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Install Nightly Rust toolchain
      - uses: CERT/setup-rust@ee9ecd55933a4ecc86043ab63feb8e0602ae319e
        with:
          channel: 'nightly'
          
      # Test
      - name: Unit tets
        run: cargo test
