name: Minusonejs build test

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Test minusonejs build
        shell: devenv shell bash -- -e {0}
        run: cd minusonejs && just build
