name: pyminusone publish pypi

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write

jobs:
  test:
    runs-on: ["ubuntu-latest"]
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build minusonejs
        shell: devenv shell bash -- -e {0}
        run: just py publish
